In [7]:
import numpy as np
import pylab
import datetime as dt
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import cm
import matplotlib.ticker as mtick
%matplotlib inline
import datetime
from datetime import date
import seaborn as sb
import time
from sklearn.svm import SVR
from sklearn.svm import SVC
import re
from sklearn.metrics import confusion_matrix
import scipy.stats as stats
from scipy.stats import mstats
from scipy.stats import ttest_ind
from sklearn import ensemble
from scipy import stats
import seaborn as sns
sns.set_style("whitegrid")
sns.color_palette("Set2", 10)
sns.set_context("notebook", font_scale=1.5, rc={"lines.linewidth": 2.5})
import sklearn
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
from sklearn.decomposition import PCA 
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from scipy import stats
from sklearn.cluster import KMeans
from sklearn.preprocessing import normalize
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import TruncatedSVD

from nltk.tokenize import WordPunctTokenizer
from nltk.corpus import stopwords # Import the stop word list
from nltk.tokenize import WordPunctTokenizer
import re
from bs4 import BeautifulSoup

In [5]:
tweets1 = pd.read_csv('C://Users/ezzan/Downloads/tmdb_5000_movies.csv.zip')
tweets1.dtypes

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
dtype: object

In [15]:

tweets1["overview"] = tweets1["overview"].astype(np.str)
tweets1["production_companies"] = tweets1["production_companies"].astype(np.str)
tweets1["revenue"] = tweets1["revenue"].astype(np.str)
tweets1["genres"] = tweets1["genres"].astype(np.str)
tweets1

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,"keywords:{""id"": 9964","keywords:{""id"": 9970","keywords:{""id"": 9974","keywords:{""id"": 9977","keywords:{""id"": 9986","keywords:{""id"": 9988","keywords:{""id"": 9989","keywords:{""id"": 999","keywords:{""id"": 9990","keywords:{""id"": 9995"
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,0,0,0,0,0,0,0,0,0,0
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,0,0,0,0,0,0,0,0,0,0
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,0,0,0,0,0,0,0,0,0,0
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,0,0,0,0,0,0,0,0,1,0
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,0,0,0,0,0,0,0,0,0,0
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,0,0,0,0,0,0,0,0,0,0
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,0,0,0,0,0,0,0,0,0,0
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...",...,0,0,0,0,0,0,0,0,0,0
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...",...,0,0,0,0,0,0,0,0,0,0
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...",...,0,0,0,0,0,0,0,0,0,0
10,270000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.superman.com,1452,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Superman Returns,Superman returns to discover his 5-year absenc...,57.925623,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...",...,0,0,0,0,0,0,0,0,0,0
11,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://www.mgm.com/view/movie/234/Quantum-of-S...,10764,"[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",en,Quantum of Solace,Quantum of Solace continues the adventures of ...,107.928811,"[{""name"": ""Eon Productions"", ""id"": 7576}]",...,0,0,0,0,0,0,0,0,0,0
12,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,58,"[{""id"": 616, ""name"": ""witch""}, {""id"": 663, ""na...",en,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,145.847379,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,0,0,0,0,0,0,0,0,0,0
13,255000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://disney.go.com/the-lone-ranger/,57201,"[{""id"": 1556, ""name"": ""texas""}, {""id"": 2673, ""...",en,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,49.046956,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,0,0,0,0,0,0,0,0,0,0
14,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.manofsteel.com/,49521,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Man of Steel,A young boy learns that he has extraordinary p...,99.398009,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,0,0,0,0,0,0,0,0,0,0
15,225000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...",NaN,2454,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,The Chronicles of Narnia: Prince Caspian,One year after their incredible adventures in ...,53.978602,"[{""name"": ""Walt Disney"", ""id"": 5888}, {""name"":...",...,0,0,0,0,0,0,0,0,0,0
16,220000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://marvel.com/avengers_movie/,24428,"[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",en,The Avengers,When an unexpected enemy emerges and threatens...,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,0,0,0,0,0,0,0,0,0,0
17,380000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://disney.go.com/pirates/index-on-stranger...,1865,"[{""id"": 658, ""name"": ""sea""}, {""id"": 1316, ""nam...",en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,135.413856,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,0,0,0,0,0,0,0,0,0,0
18,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",http://www.sonypictures.com/movies/meninblack3/,41154,"[{""id"": 4379, ""name"": ""time travel""}, {""id"": 5...",en,Men in Black 3,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,"[{""name"": ""Amblin Entertainment"", ""id"": 56}, {...",...,0,0,0,0,0,0,0,0,0,0
19,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.thehobbit.com/,122917,"[{""id"": 417, ""name"": ""corruption""}, {""id"": 603...",en,The Hobbit: The Battle of the Five Armies,Immediately after the events of The Desolation...,120.965743,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...",...,0,0,0,0,0,0,0,0,0,0
20,215000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.theamazingspiderman.com,1930,"[{""id"": 1872, ""name"": ""loss of father""}, {""id""...",en,The Amazing Spider-Man,Peter Parker is an outcast high schooler aband...,89.866276,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,0,0,0,0,0,0,0,0,0,0
21,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.robinhoodthemovie.com/,20662,"[{""id"": 4147, ""name"": ""robin hood""}, {""id"": 43...",en,Robin Hood,When soldier Robin happens upon the dying Robe...,37.668301,"[{""name"": ""Imagine Entertainment"", ""id"": 23}, ...",...,0,0,0,0,0,0,0,0,0,0
22,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.thehobbit.com/,57158,"[{""id"": 603, ""name"": ""elves""}, {""id"": 604, ""na...",en,The Hobbit: The Desolation of Smaug,"The Dwarves, Bilbo and Gandalf have successful...",94.370564,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...",...,0,0,0,0,0,0,0,0,0,0
23,180000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.goldencompassmovie.com/index_german...,2268,"[{""id"": 392, ""name"": ""england""}, {""id"": 1461, ...",en,The Golden Compass,"After overhearing a shocking secret, precociou...",42.990906,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...",...,0,0,0,0,0,0,0,0,0,0
24,207000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",NaN,254,"[{""id"": 774, ""name"": ""film business""}, {""id"": ...",en,King Kong,"In 1933 New York, an overly ambitious movie pr...",61.226010,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...",...,0,0,0,0,0,0,0,0,0,0
25,200000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://www.titanicmovie.com,597,"[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",en,Titanic,"84 years later, a 101-year-old woman named Ros...",100.025899,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,0,0,0,0,0,0,0,0,0,0
26,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://marvel.com/captainamericapremiere,271110,"[{""id"": 393, ""name"": ""civil war""}, {""id"": 6091...",en,Captain America: Civil War,"Following the events of Age of Ultron, the col...",198.372395,"[{""name"": ""Studio Babelsberg"", ""id"": 264}, {""n...",...,0,0,0,0,0,0,0,0,0,0
27,209000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 28, ""n...",NaN,44833,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 4410, ""...",en,Battleship,"When mankind beams a radio signal into space, ...",64.928382,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,0,0,0,0,0,0,0,0,0,0
28,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.jurassicworld.com/,135397,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,Twenty-two years after the events of Jurassic ...,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...",...,0,0,0,0,0,0,0,0,0,0
29,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.skyfall-movie.com,37724,"[{""id"": 470, ""name"": ""spy""}, {""id"": 4289, ""nam...",en,Skyfall,When Bond's latest assignment goes gravely wro...,93.004993,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4773,27000,"[{""id"": 35, ""name"": ""Comedy""}]",http://www.miramax.com/movie/clerks/,2292,"[{""id"": 1361, ""name"": ""salesclerk""}, {""id"": 30...",en,Clerks,Convenience and video store clerks Dante and R...,19.748658,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",...,0,0,0,0,0,0,0,0,0,0
4774,27000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",NaN,42497,"[{""id"": 1566, ""name"": ""dream""}, {""id"": 13059, ...",en,Pink Narcissus,An erotic poem set in the fantasies of a young...,0.027811,"[{""name"": ""Strand Releasing"", ""id"": 3923}]",...,0,0,0,0,0,0,0,0,0,0
4775,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...",NaN,33693,"[{""id"": 171993, ""name"": ""mumblecore""}]",en,Funny Ha Ha,"Unsure of what to do next, 23-year-old Marnie ...",0.362633,[],...,0,0,0,0,0,0,0,0,0,0
4776,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,14585,"[{""id"": 1438, ""name"": ""office""}, {""id"": 9673, ...",en,In the Company of Men,Two business executives--one an avowed misogyn...,2.634007,"[{""name"": ""Alliance Atlantis Communications"", ...",...,0,0,0,0,0,0,0,0,0,0
4777,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,185465,[],en,Manito,"Fifteen years ago, their Washington Heights ne...",0.039264,[],...,0,0,0,0,0,0,0,0,0,0
4778,0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,38780,"[{""id"": 10022, ""name"": ""rampage""}, {""id"": 1454...",en,Rampage,The boredom of small town life is eating Bill ...,7.101197,"[{""name"": ""Boll Kino Beteiligungs GmbH & Co. K...",...,0,0,0,0,0,0,0,0,0,0
4779,0,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,14022,"[{""id"": 305, ""name"": ""moon""}, {""id"": 490, ""nam...",en,Slacker,"Presents a day in the life in Austin, Texas am...",3.320622,[],...,0,0,0,0,0,0,0,0,0,0
4780,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 80, ""n...",NaN,366967,[],en,Dutch Kills,A desperate ex-con is forced to gather his old...,0.038143,[],...,0,0,0,0,0,0,0,0,0,0
4781,22000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",https://www.facebook.com/DrySpellMovie,255266,"[{""id"": 13043, ""name"": ""dating""}, {""id"": 15160...",en,Dry Spell,Sasha tries to get her soon-to-be ex husband K...,0.048948,[],...,0,0,0,0,0,0,0,0,0,0
4782,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10751, ""n...",NaN,17345,"[{""id"": 186, ""name"": ""christianity""}, {""id"": 4...",en,Flywheel,"Jay Austin wants to sell you a used car, but w...",1.048524,[],...,0,0,0,0,0,0,0,0,0,0
4783,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 27, ""n...",NaN,226458,"[{""id"": 9712, ""name"": ""possession""}]",en,Backmask,"During an all-night, drug-fueled party at an a...",3.619167,"[{""name"": ""GO Productions"", ""id"": 2943}, {""nam...",...,0,0,0,0,0,0,0,0,0,0
4784,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...",http://www.thepuffychairmovie.com,24055,"[{""id"": 171993, ""name"": ""mumblecore""}]",en,The Puffy Chair,Josh's life is pretty much in the toilet. He's...,1.243955,[],...,0,0,0,0,0,0,0,0,0,0
4785,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,287625,[],en,Stories of Our Lives,Created by the members of a Nairobi-based arts...,0.327794,[],...,0,0,0,0,0,0,0,0,0,0
4786,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,44990,"[{""id"": 10183, ""name"": ""independent film""}]",en,Breaking Upwards,"'Breaking Upwards' explores a young, real-life...",0.674570,[],...,0,0,0,0,0,0,0,0,0,0
4787,0,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",NaN,86304,"[{""id"": 9715, ""name"": ""superhero""}]",en,All Superheroes Must Die,"Masked vigilantes Charge (Jason Trost), Cutthr...",3.545991,"[{""name"": ""Grindfest"", ""id"": 18818}]",...,0,0,0,0,0,0,0,0,0,0
4788,12000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 35, ""nam...",NaN,692,"[{""id"": 237, ""name"": ""gay""}, {""id"": 900, ""name...",en,Pink Flamingos,Notorious Baltimore criminal and underground f...,4.553644,"[{""name"": ""Dreamland Productions"", ""id"": 407}]",...,0,0,0,0,0,0,0,0,0,0
4789,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,39851,"[{""id"": 6782, ""name"": ""addiction""}, {""id"": 155...",en,Clean,"After losing her husband to a heroin overdose,...",1.464566,[],...,0,0,0,0,0,0,0,0,0,0
4790,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10769, ""n...",NaN,13898,[],fa,Ø¯Ø§ÛŒØ±Ù‡,Various women struggle to function in the oppr...,1.193779,"[{""name"": ""Jafar Panahi Film Productions"", ""id...",...,0,0,0,0,0,0,0,0,0,0
4791,13,"[{""id"": 27, ""name"": ""Horror""}]",http://tincanmanthemovie.com/,157185,"[{""id"": 14903, ""name"": ""home invasion""}]",en,Tin Can Man,Recently dumped by his girlfirend for another ...,0.332679,"[{""name"": ""Park Films"", ""id"": 21871}, {""name"":...",...,0,0,0,0,0,0,0,0,0,0
4792,20000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...",NaN,36095,"[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",ja,ã‚­ãƒ¥ã‚¢,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,"[{""name"": ""Daiei Studios"", ""id"": 881}]",...,0,0,0,0,0,0,0,0,0,0
4793,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,182291,"[{""id"": 718, ""name"": ""confession""}, {""id"": 100...",en,On The Downlow,Isaac and Angel are two young Latinos involved...,0.029757,"[{""name"": ""Iconoclast Films"", ""id"": 26677}]",...,0,0,0,0,0,0,0,0,0,0
4794,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 27, ""n...",NaN,286939,[],en,Sanctuary: Quite a Conundrum,"It should have been just a normal day of sex, ...",0.166513,"[{""name"": ""Gold Lion Films"", ""id"": 37870}, {""n...",...,0,0,0,0,0,0,0,0,0,0
4795,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,124606,"[{""id"": 10726, ""name"": ""gang""}, {""id"": 33928, ...",en,Bang,A young woman in L.A. is having a bad day: she...,0.918116,"[{""name"": ""Asylum Films"", ""id"": 10571}, {""name...",...,0,0,0,0,0,0,0,0,0,0
4796,7000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.primermovie.com,14337,"[{""id"": 1448, ""name"": ""distrust""}, {""id"": 2101...",en,Primer,Friends/fledgling entrepreneurs invent a devic...,23.307949,"[{""name"": ""Thinkfilm"", ""id"": 446}]",...,0,0,0,0,0,0,0,0,0,0
4797,0,"[{""id"": 10769, ""name"": ""Foreign""}, {""id"": 53, ...",NaN,67238,[],en,Cavite,"Adam, a security guard, travels from Californi...",0.022173,[],...,0,0,0,0,0,0,0,0,0,0
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,0,0,0,0,0,0,0,0,0,0
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,0,0,0,0,0,0,0,0,0,0
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,0,0,0,0,0,0,0,0,0,0
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,0,0,0,0,0,0,0,0,0,0
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,0,0,0,0,1,0,0,0,0,0

In [29]:
print(type(keywords))

<class 'str'>

In [ ]:

def clean_tweet(column_name):
    name=set()
    for name_string in tweets1[column_name]:
        name.update(name_string.split(', '))
    name=sorted(name)
    return name

genres=clean_tweet('genres')
#Add one column for every genre in the dataframe
for genres in genres:
    tweets1["genres:"+genres] = [int(genres in g.split(', ')) for g in tweets1.genres]
    
keywords=clean_tweet('keywords')
#Add one column for every genre in the dataframe
for keywords in keywords:
    tweets1["keywords:"+keywords] = [int(keywords in g.split(', ')) for g in tweets1.keywords]

'{"id": 99'

In [13]:
def plot_column(column_name,n_elem_display=0):
    name=clean(column_name)
    dummy_name=pd.DataFrame()
    for n in name:
        dummy_name[n]=[int(n in nm.split(', ')) for nm in tweets1[column_name]] 
    
    namelist=[n for n in name]
    nlt=dummy_name[namelist].sum()
    nlt=nlt.sort_values(axis=0,ascending=False)
    if n_elem_display !=0:
     return nlt[:n_elem_display].plot(kind = "bar",figsize=(50,50))
    else:
     return nlt[:].plot(kind = "bar",figsize=(10,5))

In [ ]:
for i in range(len(tweets1)):
    #if( (i+1)%10000 == 0 ):
        #print "Tweets %d of %d has been processed" % ( i+1, nums[1] )                                                                    
    tweets1['overview'][i] = clean_tweet(tweets1['overview'][i])

In [ ]:
tweets1.iloc[10,0]

In [ ]:
x = tweets1.drop(['revenue'], axis=1)
y = tweets1[["revenue"]]

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [ ]:
plot_column("genres")

In [ ]:
count_vect = CountVectorizer()

In [ ]:
train_data_bow = count_vect.fit_transform(X_train["genres"])
test_data_bow = count_vect.transform(X_test["genres"])

train_data_bow1 = count_vect.fit_transform(X_train["keywords"])
test_data_bow1 = count_vect.transform(X_test["keywords"])


train_data_tfid = tfid_vect.fit_transform(X_train['keywords'])
test_data_tfid = tfid_vect.transform(X_test['keywords'])
train_data_tfid.shape

In [ ]:
rfc = ensemble.RandomForestRegressor()
crs = cross_val_score(rfc, train_data_bow, Y_train, cv=5)
print("Cross-Valid Fold Results are: ",crs)
print("Mean of Folds are = ",crs.mean())

In [ ]:
rfc = ensemble.RandomForestRegressor()
crs = cross_val_score(rfc, train_data_bow1, Y_train, cv=5)
print("Cross-Valid Fold Results are: ",crs)
print("Mean of Folds are = ",crs.mean())

In [ ]:
svc = SVR()
crs =cross_val_score(svc, train_data_bow, Y_train, cv=5)
print("Cross-Valid Fold Results are: ",crs)
print("Mean of Folds are = ",crs.mean())

In [ ]:

svc = SVR()
crs =cross_val_score(svc, train_data_bow1, Y_train, cv=5)
print("Cross-Valid Fold Results are: ",crs)
print("Mean of Folds are = ",crs.mean())

In [ ]:


gbc = ensemble.GradientBoostingRegressor()
crs =cross_val_score(gbc, train_data_bow, Y_train, cv=10)
print("Cross-Valid Fold Results are: ",crs)
print("Mean of Folds are = ",crs.mean())

In [30]:
lr = LogisticRegression()
crs = cross_val_score(lr, train_data_bow, Y_train, cv=10)
print("Cross-Valid Fold Results are: ",crs)
print("Mean of Folds are = ",crs.mean())

tweets

NameError: name 'train_data_bow' is not defined

In [ ]:
tfid_vect = TfidfVectorizer()

In [ ]:

tfidf_vector =  TfidfVectorizer(norm='l2', use_idf=True, smooth_idf=False, sublinear_tf=True,
                                max_df=0.5, # drop words with df of greater than .5                                
                                min_df=2, # words must occur twice
                                stop_words='english', 
                                lowercase=True, # lowercase everything
                               )

train_data_tfidf = tfidf_vector.fit_transform(X_train['keywords'])
test_data_tfidf = tfidf_vector.transform(X_test['keywords'])